config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  devise_scope :user do
    #root :to => "users/sessions#new"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end

  resources :products do
    resources :reviews, only: [:create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "products#index"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :reviews

  PER = 15

  scope :display_list, -> (page) { page(page).per(PER) }

  scope :on_category, -> (category) { where(category_id: category) }
  scope :sort_order, -> (order) { order(order) }

  scope :category_products, -> (category, page) { 
    on_category(category).
    display_list(page)
  }

  scope :sort_products, -> (sort_order, page) {
    on_category(sort_order[:sort_category]).
    sort_order(sort_order[:sort]).
    display_list(page)
  }

  scope :sort_list, -> {
    {
      "並び替え" => "",
      "価格の安い順" => "price asc",
      "価格の高い順" => "price desc",
      "出品の古い順" => "updated_at asc",
      "出品の新しい順" => "updated_at desc"
    }
  }

  def reviews_new
    reviews.new
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    if sort_params.present?
      @sorted = sort_params[:sort]
      @category = Category.request_category(sort_params[:sort_category])
      @products = Product.sort_products(sort_params, params[:page])
    elsif params[:category].present?
      @category = Category.request_category(params[:category])
      @products = Product.category_products(@category, params[:page])
    else
      @products = Product.display_list(params[:page])
    end

    @categories = Category.all
    @major_category_names = Category.major_categories
    @sort_list = Product.sort_list
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews
    @review = @reviews.new
  end

  def new
    @product = Product.new
    @categories = Category.all
  end

  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to product_url @product
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.all
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to product_url @product
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url
  end

  private
   def product_params
     params.require(:product).permit(:name, :description, :price, :category_id)
   end

   def sort_params
     params.permit(:sort, :sort_category)
   end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>
<h1>Update Products</h1>

<%= form_with model: @product do |f| %>
 <%= f.text_field :name %>
 <%= f.text_area :description %>
 <%= f.number_field :price %>
 <%= f.collection_select(:category_id, @categories, :id, :name) %>
 <%= f.submit "Update" %>
<% end %>

<%= link_to "Back", products_path %>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

<div class="col-2">
  <%= render partial: "layouts/sidebar", locals: { categories: @categories, major_category_names: @major_category_names } %>
</div>

<div class="container">
  <% if @category.present? %>
    <%= link_to "トップ", "#", category: @major_category_name %> > <%= @category.name %>
    <h1><%= @category.name %>の商品一覧<%= @products.count %>件</h1>
    <%= form_with url: products_path, method: :get, local: true, class: "form-inline" do |f| %>
      <%= f.hidden_field :sort_category, value: @category.id %>
      並び替え
      <% if @sorted.present? %>
        <%= f.select :sort, @sort_list, { selected: @sorted }, onChange: "javascript: this.form.submit();", class: "form-inline ml-2" %>
      <% else %>
        <%= f.select :sort, @sort_list, {}, onChange: "javascript: this.form.submit();", class: "form-inline ml-2" %>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="container mt-4">
  <div class="row w-100">
    <% @products.each do |product| %>
      <div class="col-3">
        <%= link_to product_path(product) do %>
          詳細
        <% end %>
        <div class="row">
          <div class="col-12">
            <p class="samuraimart-product-label mt-2">
              <%= product.name %><br>
              <label>¥<%= product.price %></label>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= link_to "New", new_product_path %>
<%= paginate @products %>

app/views/products/new.html.erb
<h1>New Products</h1>
<p>Find me in app/views/products/new.html.erb</p>
<%= form_with model: @product do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :description %>
  <%= f.number_field :price %>
  <%= f.collection_select(:category_id, @categories, :id, :name) %>
  <%= f.submit "Create" %>
<% end %>

<%= link_to "Back", products_path %>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>
<%= link_to "Back", products_path %>

<div class="col">
  <div class="d-flex flex-column">
    <h1 class="">
      <%= @product.name %>
    </h1>
    <p class="">
      <%= @product.description %>
    </p>
    <hr>
    <p class="d-flex align-items-end">
      ￥<%= @product.price %>(税込)
    </p>
    <hr>
  </div>
</div>